package model;



/**
 * Auto generated by hbm2java
 */
public class Auto  implements java.io.Serializable {


     private String targa;
     private String marca;
     private String modello;
     private double costoGiornallero;

    public Auto() {
    }

    public Auto(String targa, String marca, String modello, double costoGiornallero) {
       this.targa = targa;
       this.marca = marca;
       this.modello = modello;
       this.costoGiornallero = costoGiornallero;
    }
   
    public String getTarga() {
        return this.targa;
    }
    
    public void setTarga(String targa) {
        this.targa = targa;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModello() {
        return this.modello;
    }
    
    public void setModello(String modello) {
        this.modello = modello;
    }
    public double getCostoGiornallero() {
        return this.costoGiornallero;
    }
    
    public void setCostoGiornallero(double costoGiornallero) {
        this.costoGiornallero = costoGiornallero;
    }


// è mysql server che non funziona sul tuo pc

}


