package model;


import java.util.Date;

/**
 * Noleggi generated by hbm2java
 */
public class Noleggi  implements java.io.Serializable {


     private Integer codiceNoleggio;
     private String auto;
     private String socio;
     private Date inizio;
     private Date fine;
     private boolean autoRestituita;

    public Noleggi() {
    }

    public Noleggi(String auto, String socio, Date inizio, Date fine, boolean autoRestituita) {
       this.auto = auto;
       this.socio = socio;
       this.inizio = inizio;
       this.fine = fine;
       this.autoRestituita = autoRestituita;
    }
   
    public Integer getCodiceNoleggio() {
        return this.codiceNoleggio;
    }
    
    public void setCodiceNoleggio(Integer codiceNoleggio) {
        this.codiceNoleggio = codiceNoleggio;
    }
    public String getAuto() {
        return this.auto;
    }
    
    public void setAuto(String auto) {
        this.auto = auto;
    }
    public String getSocio() {
        return this.socio;
    }
    
    public void setSocio(String socio) {
        this.socio = socio;
    }
    public Date getInizio() {
        return this.inizio;
    }
    
    public void setInizio(Date inizio) {
        this.inizio = inizio;
    }
    public Date getFine() {
        return this.fine;
    }
    
    public void setFine(Date fine) {
        this.fine = fine;
    }
    public boolean isAutoRestituita() {
        return this.autoRestituita;
    }
    
    public void setAutoRestituita(boolean autoRestituita) {
        this.autoRestituita = autoRestituita;
    }




}


