package model;



/**
 * Soci generated by hbm2java
 */
public class Soci  implements java.io.Serializable {


     private String cf;
     private String cognome;
     private String nome;
     private String indirizzo;
     private String telefono;

    public Soci() {
    }

    public Soci(String cf, String cognome, String nome, String indirizzo, String telefono) {
       this.cf = cf;
       this.cognome = cognome;
       this.nome = nome;
       this.indirizzo = indirizzo;
       this.telefono = telefono;
    }
   
    public String getCf() {
        return this.cf;
    }
    
    public void setCf(String cf) {
        this.cf = cf;
    }
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getIndirizzo() {
        return this.indirizzo;
    }
    
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


